INSERT INTO "USER_HAS_ROLE" ("USER_ID", "ROLE_ID") VALUES (1,1);
INSERT INTO "USER_HAS_ROLE" ("USER_ID", "ROLE_ID") VALUES (2,2);
INSERT INTO "USER_HAS_ROLE" ("USER_ID", "ROLE_ID") VALUES (3,3);
INSERT INTO "USER_HAS_ROLE" ("USER_ID", "ROLE_ID") VALUES (4,4);
