INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (1,'Паспорт гражданина Российской федерации',1,0);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (2,'Паспорт моряка',1,1);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (3,'Общегражданский заграничный паспорт гражданин',1,2);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (4,'Паспорт иностранного гражданина',1,3);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (5,'Свидетельство о рождении',1,4);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (6,'Удостоверение личности военнослужащего',1,5);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (7,'Удостоверение личности лица без гражданства',1,6);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (8,'Временное удостоверение личности, выдаваемое ',1,7);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (9,'Военный билет военнослужащего срочной службы',1,8);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (10,'Вид на жительство иностранного гражданина или',1,9);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (11,'Справка об освобождении из мест лишения свобо',1,10);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (12,'Паспорт гражданина СССР',1,11);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (13,'Паспорт дипломатический',1,12);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (14,'Паспорт служебный (кроме паспорта моряка и ди',1,13);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (15,'Свидетельство о возвращении из стран СНГ',1,14);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (16,'Справка об утере паспорта',1,15);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (17,'Удостоверение депутата',1,16);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (25,'СТС',2,25);
INSERT INTO "SUPPORTING_DOCUMENT" ("ID", "NAME", "CATEGORY_ID", "DOC_TYPE") VALUES (26,'ПТС',2,26);